site_name: sasha-ken
site_url: https://quinn-sasha.github.io/sasha-ken/

theme:
  name: material

  language: ja
  feature:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.instant
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - content.tabs.link
    - search.highlight
    - content.code.annotation
    - content.code.copy
    - content.code.select
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: white 
      accent: lime

plugins:
  - search

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://x.com/Sasha_Quinnk
      name: Sasha_Quinnk
    - icon: fontawesome/brands/github
      link: https://github.com/quinn-sasha
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sasha-quinn-9551542b1/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - tables

